# plane configuration file for LowPressure-1/3CellStaggered3Planes-MWDC (XX'X''UU'U''VV'V'')
#
# center wire ID is zero-origin
# the detector position is measured relatively to the detector center
# the coordinate should be defined in right-handed systeme
# the origin of the angle is set to positive direction of x-axis

- x0:
    z:  -40.
    nWire:  &nwire  24
    cellSize:  &cell  10.
    angle:  180.
    center:  11.5

- x1:
    z:  -30.
    nWire:  *nwire
    cellSize:  *cell
    angle:  180.
    center:  67/6

- x2:
    z:  -20.
    nWire:  *nwire
    cellSize:  *cell
    angle:  180.0
    center:  71/6

- u0:
    z:  -10.
    nWire:  *nwire
    cellSize:  *cell
    angle:  150.
    center: 11.5

- u1:
    z:  0.
    nWire:  *nwire
    cellSize:  *cell
    angle:  150.
    center:  67/6

- u2:
    z:  10.
    nWire:  *nwire
    cellSize:  *cell
    angle:  150.
    center:  71/6

- v0:
    z:  20.
    nWire:  *nwire
    cellSize:  *cell
    angle:  210.
    center:  11.5

- v1:
    z:  30.
    nWire:  *nwire
    cellSize:  *cell
    angle:  210.
    center:  67/6

- v2:
    z:  40.
    nWire:  *nwire
    cellSize:  *cell
    angle:  210.
    center:  71/6

