# plane configuration file for LP-MWDC type-D (X'XUV)
# Last Modified : 2016-04-11 15:53:02 JST (Shinsuke OTA)
#
# - z position is relative to the detector center
#
# - Center wire id is zero-origin.
#
# - Angle is defined so that the coordinate system is the right-handed system.
#
# - The angle of axis of each plane to the horizontal axis.
 
- x1:
    z:         -13.5
    nWire:    &nwire 24
    cellSize: &cell 9.
    angle:    180.
    center:    11.
- x2:
    z:        -4.5
    nWire:    *nwire
    cellSize: *cell
    angle:    180
    center:    11.5
- u:
    z:         4.5
    nWire:    *nwire
    cellSize: *cell
    angle:    150
    center:    11.
- v:
    z:        13.5
    nWire:    *nwire
    cellSize: *cell
    angle:    225
    center:    12.5
