# plane configuration file for LP-MWDC type-C
#* Last Modified : 2016-03-28 14:48:55 JST (ota)
#
# z position is relative to the detector center
# Center wire id is zero-origin.
# Angle is defined so that the coordinate system is the right-handed system.
#
# The angle of axis of each plane to the horizontal axis.

- x1: #X
    z:         -2.4
    nWire:    &nwire  16
    cellSize: &cell   5.
    angle:    &xangle 180.
    center:    9.0
- x2: #X'
    z:         -7.2
    nWire:    *nwire
    cellSize: *cell
    angle:    *xangle
    center:    8.5
- y1: #Y
    z:         -12.0
    nWire:    *nwire
    cellSize: *cell
    angle:    &yangle 90.
    center:    9.
- y2: #Y'
    z:         -16.8
    nWire:    *nwire
    cellSize: *cell
    angle:    *yangle
    center:    8.5
